Script started on 2017年03月07日 (週二) 23時48分43秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pq[Kwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l
user.email=wijaya.febrina@yahoo.co.id
user.name=FebrinaWijaya
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git clone https://github.com/FebrinaWIja[K[K[Kijaya/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m 
Script done on 2017年03月07日 (週二) 23時49分39秒
